name: Gitlab Runner Service
on: [repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Gitlab Runner
        uses: torbenraab/gitlab-runner-action@main
        with:
          token: "${{ github.event.client_payload.token }}"
          name: ${{ github.run_id }}
          tag-list: "crosscicd"
          gitlab-instance: "${{ github.event.client_payload.url }}"