name: Gitlab Runner Service
on: [repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Gitlab Runner
        uses: torbenraab/gitlab-runner-action@v0.0.4
        with:
          token: "${{ github.event.client_payload.token }}"
          name: ${{ github.run_id }}
          gitlab-instance: "${{ github.event.client_payload.url }}"
          job-count: "${{ github.event.client_payload.job_count || 1 }}"